server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "ai_companion"
  sslmode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
llm:
  provider: "ollama_llm"  #llm 提供商
  model: "qwen2.5:latest" #llm 模型
  baseUrl: "http://custom-server:11434" #llm提供商提供的baseUrl

app:
  webSocketPort: 8081
  rpcPort: 8082
